# Generated by Django 2.0.2 on 2018-03-02 01:14

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='custom_filename',
        ),
        migrations.RemoveField(
            model_name='kitten',
            name='image',
        ),
        migrations.RemoveField(
            model_name='kitten',
            name='pdf',
        ),
        migrations.AddField(
            model_name='cat',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='video',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
