# Generated by Django 2.0.2 on 2018-03-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_auto_20180302_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitten',
            old_name='video',
            new_name='track',
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_no',
            field=models.CharField(default='123', max_length=30),
            preserve_default=False,
        ),
    ]
