# Generated by Django 2.0.2 on 2018-03-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0003_auto_20180302_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='disc_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kitten',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='kitten',
            name='track_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
