# Generated by Django 2.0.2 on 2018-03-07 00:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('release', '0004_auto_20180302_0132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Release',
        ),
    ]
