# Generated by Django 2.0.2 on 2018-03-07 00:20

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('release', '0005_auto_20180307_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kitten',
            new_name='Track',
        ),
    ]
