# Generated by Django 2.0.2 on 2018-03-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_auto_20180307_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='in_number',
            field=models.IntegerField(choices=[('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4)], default='ONE'),
        ),
    ]
