# Generated by Django 2.0.2 on 2018-03-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0009_auto_20180307_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
