# Generated by Django 2.0.2 on 2018-03-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0010_auto_20180307_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disc',
            name='compilation',
        ),
        migrations.AlterField(
            model_name='disc',
            name='number',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')], default=1),
        ),
    ]
