# Generated by Django 2.0.2 on 2018-03-07 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0011_auto_20180307_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='mother',
        ),
        migrations.AddField(
            model_name='track',
            name='disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='release.Disc'),
        ),
    ]
