# Generated by Django 2.0.2 on 2018-03-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0012_auto_20180307_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['track_no']},
        ),
        migrations.AlterField(
            model_name='track',
            name='track_no',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
